Closes #63
MobileApps-Cascadia/orca-stars-android pull request #69
Opened 2020-01-29 00:21 UTC by JoshuaAaron

Added the OrcaStars website logo, about us information, email, and youtube links

2020-01-29 08:31 UTC, charlesmsy requested changes
Could we also get the "AboutUsFragment" with this?

2020-01-31 02:19 UTC, VBeegle requested changes
This pull request commit has not added the missing AboutUsFragment and corresponding layout. Please make sure to add them to your commit before merging

2020-01-31 18:03 UTC, JoshuaAaron commented
Oh wow, I totally missed that it didn't add those files. It should good to go now. Sorry team

2020-01-31 23:39 UTC, VBeegle approved these changes

2020-02-01 01:24 UTC, charlesmsy approved these changes

2020-02-01 01:26 UTC, merged